sudo: false
dist: xenial
language: node_js
git:
  depth: 3
node_js:
  - "6"
  - "8"
before_install:
  - if [[ `npm -v` != 5* ]]; then npm install -g npm@5; fi
  - "export TRAVIS_COMMIT_MSG=\"`git log --format=%B --no-merges -n 1`\""
install:
  - yarn install
  - yarn run install-peers
script:
  - yarn test
cache:
  yarn: true
  directories:
    - node_modules
