export default {
    ADD_ON_LIST: 'addOnList',
    CHECKBOX: 'checkbox',
    DATE_INPUT: 'dateInput',
    DECIMAL_INPUT: 'decimalInput',
    DECIMAL_INPUT_OR_IGNORE: 'decimalInputOrIgnore',
    FORM: 'form',
    FORM_GROUP: 'formGroup',
    TABS: 'tabs',
    RADIO: 'radio',
    RADIO_SECTIONS: 'radioSections',
    RADIO_TABLE: 'radioTable',
    SELECT: 'select',
    TEXT_BOX: 'textBox',
    TEXT_INPUT: 'textInput',
    TEXT_INPUT_OR_IGNORE: 'textInputOrIgnore',
    TEXT_INPUT_OR_NO_ANSWER: 'textInputOrNoAnswer',
    TEXT_WITH_BADGE: 'textWithBadge',
    TITLE: 'title',
    TOTAL: 'total',
    YES_NO_BUTTONS: 'yesNoButtons',
    TEXT_INPUT_AUTO_CALCULATED: 'textInputAutoCalculated'
};
