export default {
    ADD_ON_LIST: 'addOnList',
    CALC: 'calc',
    CHECKBOX: 'checkbox',
    DATE_INPUT: 'dateInput',
    DECIMAL_INPUT: 'decimalInput',
    DECIMAL_INPUT_OR_IGNORE: 'decimalInputOrIgnore',
    MULTI_SELECT: 'multiSelect',
    RADIO: 'radio',
    RADIO_SECTIONS: 'radioSections',
    RADIO_TABLE: 'radioTable',
    SELECT: 'select',
    SUM: 'sum',
    TEXT_INPUT: 'textInput',
    TEXT_INPUT_OR_IGNORE: 'textInputOrIgnore',
    TEXT_INPUT_OR_NO_ANSWER: 'textInputOrNoAnswer',
    TEXT_WITH_BADGE: 'textWithBadge',
    TIME_PICKER: 'timePicker',
    TITLE: 'title',
    YES_NO_BUTTONS: 'yesNoButtons'
};
