export const types = {
    ADDON_LIST: 'AddOnList',
    CHECKBOX: 'checkbox',
    DATE: 'date',
    EMAIL: 'email',
    INT: 'int',
    INFO_TEXT_BOX: 'infoTextBox',
    INT_ALLOW_ZERO: 'intAllowZero',
    LABEL: 'label',
    LINE: 'line',
    MASKED_DATE: 'maskedDate',
    MONEY: 'money',
    NUMBER: 'number',
    NUMBER_FORMAT: 'numberFormat',
    NUMBER_WITHOUT_LABEL: 'numberWithoutLabel',
    NUMBER_WITH_IGNORE: 'numberWithIgnore',
    PERCENTAGE: 'percentage',
    QUESTION_WITHOUT_ANSWER: 'questionWithoutAnswer',
    RADIO: 'radio',
    RADIO_TABLE: 'radioTable',
    RADIO_SECTIONS: 'radioSections',
    SELECT: 'select',
    SELECT_DISABLED: 'selectDisabled',
    SELECT_MULTIPLE: 'selectMultiple',
    SELECT_SPECIAL_OPTIONS: 'selectSpecialOptions',
    SPACE: 'space',
    SUM: 'sum',
    TEXT: 'text',
    TEXT_OR_NO_ANSWER: 'textNoAnswer',
    TEXT_WITH_IGNORE: 'textWithIgnore',
    TEXT_AREA: 'textarea',
    TITLE: 'title',
    YEAR: 'Year',
    YES_NO: 'YesNoQuestion',
    LAPEL_GROUP: 'lapelGroup'
};

// operator enum will be moved to another package in a future.
export const operator = {
    EQUALS: 'eq',
    NOT_EQUALS: 'ne',
    GREATER_THAN: 'gt',
    GREATER_OR_EQUAL_THAN: 'gte',
    LESS_THAN: 'lt',
    LESS_OR_EQUAL_THAN: 'lte',
    EXISTS: 'exists'
};
